---
# "super" - supervised learning, "semi" - semi supervised learning, "shot" - few shot learning
task: "semi"

data: "cifar10"
model: "resnet20"
augment: 
    - "Flip"
    - "Translation"
    - "Rotation"
    - "ContrastBrightness"
    - "GaussBlur"

aug_strength:
    - 0.2
    - 0.2
    - 0.2
    - 0.2
    - 0.2

eval:
    "Acc"
       
batch_size: 120
learning_rate: 0.01
momentum: 0.9
epoch: 160
optimizer: "sgd"
weight_decay: 0.0005
seed: 6759
